UiSession: fix theme initialization
eclipse-scout/scout.rt pull request #1001
Opened 2024-05-08 14:37 UTC by bschwarzent

- URL param (?theme=xyz) always takes precedence over the current theme
- Otherwise, if the model already has a theme set, use that one.
- Otherwise, use the "current theme" from the request (session attribute, cookie or default value).

A warning is only logged when the requested theme or the model theme is set but is not valid according to UiThemeHelper. When the model does not specify a theme, a default theme is assigned automatically without log message.

When the theme is determined, it is written back to the model, so the logo URL and potentially other things can be adjusted.

In Scout JS, we have no UiSession or ClientSession. For a similar functionality, the URL param is manually compared with the current theme (called "active theme").

270127

2024-05-14 09:22 UTC, fschinkel requested changes

2024-05-14 09:22 UTC, fschinkel commented on eclipse-scout-core/src/desktop/Desktop.ts
> +    if (!this.modelAdapter && this.url.hasParameter('theme')) { // only needed for Scout JS (in Scout classic, the theme URL parameter is handled in UiSession#initUiTheme)
move to DesktopAdapter

2024-05-14 15:02 UTC, fschinkel approved these changes

2024-05-21 15:19 UTC, bschwarzent commented on eclipse-scout-core/src/desktop/Desktop.ts
> +    if (!this.modelAdapter && this.url.hasParameter('theme')) { // only needed for Scout JS (in Scout classic, the theme URL parameter is handled in UiSession#initUiTheme)
Done

2024-05-21 16:31 UTC, merged