Tree: Do not send unnecessary events to server
eclipse-scout/scout.rt pull request #1234
Opened 2024-10-24 12:19 UTC by Knicksaas

- When Tree is not checkable, do not send any nodesChecked events
- Do not send empty nodesChecked events at all

2024-10-25 08:31 UTC, bschwarzent requested changes

2024-10-25 08:31 UTC, bschwarzent commented on eclipse-scout-core/src/tree/Tree.ts
> +   * an {@code nodesChecked} event to send updated nodes to java.
```suggestion
   * a `nodesChecked` event.
```

* an -> a
* The tree widget is not aware of the java part, it just emits the event and the TreeAdapter is responsible to forward that event to java.
* In TypeScript, we use backticks to format inline code in jsdoc

2024-10-25 08:31 UTC, bschwarzent commented on eclipse-scout-core/src/tree/Tree.ts
> +   * @param triggerEvent indicates, if events should be triggered or not
```suggestion
   * @param triggerEvent indicates whether events should be triggered or not. Default is true.
```

2024-10-25 08:31 UTC, bschwarzent commented on eclipse-scout-core/src/tree/Tree.ts
> -    if (this.rendered) {
Did you remove this check intentionally? It seems appropriate to keep it around the first part of `_processTreeCheckNodesResult`. Or can this only be called while the tree is rendered?

2024-10-25 08:31 UTC, bschwarzent commented on eclipse-scout-core/src/tree/TreeAdapter.ts
> +    if (!this.widget.checkable) {
Why is this flag checked here and not already in the Tree widget? It seems to make more sense not to trigger the `nodesChecked` event in the first place, e.g. in `_processTreeCheckNodesResult`.

2024-10-25 08:31 UTC, bschwarzent commented on eclipse-scout-core/src/tree/Tree.ts
> +    if (triggerEvent && eventTriggerNodes.length) {
Is that really correct? What if the last checked node is unchecked? An observer of the tree would want to be notified about any change in the list of checked nodes, even when the new list is empty.

2024-10-25 13:23 UTC, Knicksaas commented on eclipse-scout-core/src/tree/Tree.ts
> -    if (this.rendered) {
Yes, when the tree is initialized, the checked state of the nodes can already change. At this time, the tree is not rendered, but you have to notify the server about the state change.

2024-10-25 13:23 UTC, Knicksaas commented on eclipse-scout-core/src/tree/TreeAdapter.ts
> +    if (!this.widget.checkable) {
I agree. Otherwise, event listeners in TS would have been notified, but not those in java.

2024-10-25 13:23 UTC, Knicksaas commented on eclipse-scout-core/src/tree/Tree.ts
> +    if (triggerEvent && eventTriggerNodes.length) {
The list of nodes does not contain all checked nodes, but all nodes which have encountered a checked-state change. When the last node was unchecked, the event holds the value: 
```json
"node": [{
  "id": "ui12",
  "...": "..."
  "checked": false
}]
```
An empty list means no nodes have changed its checked-state. Therefore, I believe this is correct.

2024-10-25 13:44 UTC, bschwarzent commented on eclipse-scout-core/src/tree/TreeAdapter.ts
> +    if (!this.widget.checkable) {
👍

2024-10-25 13:45 UTC, bschwarzent commented on eclipse-scout-core/src/tree/Tree.ts
> +    if (triggerEvent && eventTriggerNodes.length) {
Ah, I misunderstood the meaning of the `nodes` data. Thanks for the clarification!

2024-11-14 14:20 UTC, bschwarzent commented
Looks good!

2024-11-14 14:20 UTC, bschwarzent approved these changes

2024-11-14 14:20 UTC, merged