387870 Distributed Tracing
eclipse-scout/scout.rt pull request #1291
Opened 2024-12-04 15:20 UTC by work-lto

2024-12-16 10:03 UTC, work-lto commented
Todo: Adapt final commit message

2025-01-01 16:55 UTC, brunokoeferli requested changes

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.client/src/main/java/org/eclipse/scout/rt/client/extension/ui/basic/tree/AbstractTreeExtension.java
> +
Why do we need this change?

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.client.test/src/test/java/org/eclipse/scout/rt/client/context/ClientRunContextChainTest.java
> +    // 10. OpenTelemetryContextProcessor
We should discuss the order of this processor. Should it be the first element in the chain?

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.client.test/src/test/java/org/eclipse/scout/rt/client/context/ClientRunContextChainTest.java
> +    assertEquals(OpenTelemetryContextProcessor.class, c.getClass());
I miss here a simple check like for the element `1. RunMonitorCancellableProcessor for null parent`

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.ui.html.test/pom.xml
> +    <dependency>
Why is this dependency required?

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt/pom.xml
> +    <opentelemetry.version>1.44.1</opentelemetry.version>
Update to latest versions

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt/pom.xml
> +    <opentelemetry.instrumentation.alpha.version>${opentelemetry.instrumentation.version}-alpha</opentelemetry.instrumentation.alpha.version>
I would prefer duplicating the `instrumentation version` value here. It might be simpler/more clear. And the duplication is quite local (one line above), which reduces possible errors when updating the version(s).

```suggestion
    <opentelemetry.instrumentation.alpha.version>2.10.0-alpha</opentelemetry.instrumentation.alpha.version>
```

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.ui.html/src/main/java/org/eclipse/scout/rt/ui/html/json/JsonEventProcessor.java
> +
Please do not change lines without added value.

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.ui.html/src/main/java/org/eclipse/scout/rt/ui/html/json/JsonEventProcessor.java
>        LOG.info("No adapter found for event. {}", event.toSafeString());
Try to prevent unnecessary memory/cpu allocation if tracing is deactivated:
```suggestion
  protected void processEvent(JsonEvent event, JsonResponse response) {
    final IJsonAdapter<?> jsonAdapter = m_uiSession.getJsonAdapter(event.getTarget());
    if (jsonAdapter == null) {
      LOG.info("No adapter found for event. {}", event.toSafeString());
      return;
    }
    try {
      if (LOG.isDebugEnabled()) {
        LOG.debug("Handling event '{}' for adapter with ID {}", event.getType(), event.getTarget());
      }

      addNameToContext(() -> buildSpanName(event, jsonAdapter));
      jsonAdapter.handleUiEvent(event);
```

```
  protected String buildSpanName(JsonEvent event, IJsonAdapter<?> jsonAdapter) {
    return jsonAdapter.getModel().getClass().getSimpleName() + "." + event.getType();
  }
```

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.server.commons/src/main/java/org/eclipse/scout/rt/server/commons/opentelemetry/SpanNamePropagationFromDownstream.java
> +  }
Try to prevent unnecessary memory/cpu allocation if tracing is deactivated:
```suggestion
  public static void addNameToContext(Supplier<String> nameSupplier) {
    List<String> o = Context.current().get(NAME_CONTEXT_KEY);
    if (o != null) {
      o.add(nameSupplier.get());
    }
  }
```

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.shared/src/main/java/org/eclipse/scout/rt/shared/servicetunnel/ServiceUtility.java
> + * Copyright (c) 2010, 2024 BSI Business Systems Integration AG
Please revert this "no change"

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.shared/pom.xml
> +  ~ Copyright (c) 2010, 2024 BSI Business Systems Integration AG
Please revert this "no change"

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.server.commons/pom.xml
> +  ~ Copyright (c) 2010, 2024 BSI Business Systems Integration AG
Please revert this "no change"

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.server.test/pom.xml
> +    <dependency>
Why is this dependency required?

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.server.commons.test/pom.xml
> +    <dependency>
Why is this dependency required?

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.client/src/main/java/org/eclipse/scout/rt/client/opentelemetry/IOpenTelemetryExtension.java
> +public interface IOpenTelemetryExtension<OWNER> {
We should prevent usage of dummy interface just to share code. I suggest to move the `wrap` function into the class `OpenTelemetryExtensionRequest`:

```java
    new OpenTelemetryExtensionRequest<>(getOwner(), "execAction")
        .withEventInfo("id", getOwner().getActionId())
        .wrapCall(() -> super.execAction(chain), m_instrumenter);
```

`wrapCall` implementation:
```java

    public T wrapCall(Supplier<T> callable, Instrumenter<OpenTelemetryExtensionRequest<T>, Void> m_instrumenter) {
      Context parentContext = Context.current();

      if (!m_instrumenter.shouldStart(parentContext, this)) {
        return callable.get();
      }

      Context context = m_instrumenter.start(parentContext, this);
      T result;
      try (Scope ignored = context.makeCurrent()) {
        result = callable.get();
      }
      catch (Throwable t) {
        m_instrumenter.end(context, this, null, t);
        throw t;
      }
      m_instrumenter.end(context, this, null, null);
      return result;
    }

    public void wrapCall(Runnable callable, Instrumenter<OpenTelemetryExtensionRequest<T>, Void> m_instrumenter) {
      Context parentContext = Context.current();

      if (!m_instrumenter.shouldStart(parentContext, this)) {
        callable.run();
        return;
      }

      Context context = m_instrumenter.start(parentContext, this);
      try (Scope ignored = context.makeCurrent()) {
        callable.run();
      }
      catch (Throwable t) {
        m_instrumenter.end(context, this, null, t);
        throw t;
      }
      m_instrumenter.end(context, this, null, null);
    }
```

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.client/src/main/java/org/eclipse/scout/rt/client/opentelemetry/OpenTelemetryActionExtension.java
> +            .withEventInfo("id", getOwner().getActionId()));
Sample:
```suggestion
    new OpenTelemetryExtensionRequest<>(getOwner(), "execAction")
        .withEventInfo("id", getOwner().getActionId())
        .wrapCall(() -> super.execAction(chain), m_instrumenter);
```

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.client/src/main/java/org/eclipse/scout/rt/client/opentelemetry/OpenTelemetryExtensionInstrumenterFactory.java
> +        internalSet(attributes, m_requestClass, request.getOwner().getClass().getName());
`internalSet` can be removed. `AttributesBuilder.put` provides the same function and is public API.
```suggestion
        attributes.put(m_requestClass, request.getOwner().getClass().getName());
```

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.client/src/main/java/org/eclipse/scout/rt/client/opentelemetry/OpenTelemetryExtensionInstrumenterFactory.java
> +      Function<OpenTelemetryExtensionRequest<OWNER>, String> getTextFunction) {
1. Currently the instrumentation name is like `scout.scout.OpenTelemetryActionExtension` (duplication of `scout`). I would change the method signature to just receive the extension's class instance and then "calculate" the instrumentation name in this method.
2. Additionally I would remove the argument `prefix` (which leads to memory allocation during each execution)
3. Replace the "event map" on `OpenTelemetryExtensionRequest` with a `BiConsumer<OpenTelemetryExtensionRequest<OWNER>, AttributesBuilder>` for additional attributes. Again this will reduce the memory allocation.
4. Externalize the anonymous `AttributesExtractor` implementation.

Proposal:
```suggestion
  public <OWNER> Instrumenter<OpenTelemetryExtensionRequest<OWNER>, Void> createInstrumenter(
      Class<?> instrumentationClass,
      Function<OpenTelemetryExtensionRequest<OWNER>, String> getTextFunction,
      BiConsumer<OpenTelemetryExtensionRequest<OWNER>, AttributesBuilder> additionalAttributes) {
```

This would lead to following code in `OpenTelemetryExtensionInstrumenterFactory`:
```java
  public <OWNER> Instrumenter<OpenTelemetryExtensionRequest<OWNER>, Void> createInstrumenter(
      Class<?> instrumentationClass,
      Function<OpenTelemetryExtensionRequest<OWNER>, String> getTextFunction,
      BiConsumer<OpenTelemetryExtensionRequest<OWNER>, AttributesBuilder> additionalAttributesProvider) {
    SpanNameExtractor<OpenTelemetryExtensionRequest<OWNER>> spanNameExtractor = request -> request.getOwner().getClass().getSimpleName() + "." + request.getEventName();
    ScoutExtensionAttributesExtractor<OWNER> attributesExtractor = new ScoutExtensionAttributesExtractor<>(getTextFunction, additionalAttributesProvider);
    return Instrumenter.<OpenTelemetryExtensionRequest<OWNER>, Void> builder(GlobalOpenTelemetry.get(),
            "scout." + instrumentationClass.getSimpleName(),
            spanNameExtractor)
        .addAttributesExtractor(attributesExtractor)
        .setEnabled(CONFIG.getPropertyValue(OpenTelemetryTracingEnabledProperty.class))
        .buildInstrumenter();
  }

  public static class ScoutExtensionAttributesExtractor<T> implements AttributesExtractor<OpenTelemetryExtensionRequest<T>, Void> {

    private static final AttributeKey<String> OWNER_CLASS = AttributeKey.stringKey("scout.extension.owner.class");
    private static final AttributeKey<String> OWNER_DISPLAY_TEXT = AttributeKey.stringKey("scout.extension.owner.display_text");

    private final Function<OpenTelemetryExtensionRequest<T>, String> m_getTextFunction;
    private final BiConsumer<OpenTelemetryExtensionRequest<T>, AttributesBuilder> m_additionalAttributesProvider;

    public ScoutExtensionAttributesExtractor(Function<OpenTelemetryExtensionRequest<T>, String> getTextFunction, BiConsumer<OpenTelemetryExtensionRequest<T>, AttributesBuilder> additionalAttributesProvider) {
      m_getTextFunction = getTextFunction;
      m_additionalAttributesProvider = additionalAttributesProvider;
    }

    @Override
    public void onStart(AttributesBuilder attributes, Context parentContext, OpenTelemetryExtensionRequest<T> request) {
      attributes.put(OWNER_CLASS, request.getOwner().getClass().getName());
      attributes.put(OWNER_DISPLAY_TEXT, m_getTextFunction.apply(request));

      m_additionalAttributesProvider.accept(request, attributes);
    }

    @Override
    public void onEnd(AttributesBuilder attributes, Context context, OpenTelemetryExtensionRequest<T> request, @Nullable Void unused, @Nullable Throwable error) {
      // nop
    }
  }
```

and in `OpenTelemetryActionExtension`:
```java
public class OpenTelemetryActionExtension extends AbstractActionExtension<AbstractAction> {

  private static final AttributeKey<String> OWNER_ACTION_ID = AttributeKey.stringKey("scout.extension.owner.action.id");

  private Instrumenter<OpenTelemetryExtensionRequest<AbstractAction>, Void> m_instrumenter;

  public OpenTelemetryActionExtension(AbstractAction owner) {
    super(owner);
    m_instrumenter = BEANS.get(OpenTelemetryExtensionInstrumenterFactory.class).createInstrumenter(
        getClass(),
        (request) -> request.getOwner().getText(),
        (request, attributes) -> attributes.put(OWNER_ACTION_ID, request.getOwner().getActionId()));
  }

  @Override
  public void execAction(ActionActionChain chain) {
    new OpenTelemetryExtensionRequest<>(getOwner(), "execAction")
        .wrapCall(() -> super.execAction(chain), m_instrumenter);
  }
}
```

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.client/src/main/java/org/eclipse/scout/rt/client/opentelemetry/OpenTelemetryExtensionInstrumenterFactory.java
> +    private Map<String, String> m_eventMap;
To be removed in favor of `BiConsumer<OpenTelemetryExtensionRequest<OWNER>, AttributesBuilder> additionalAttributesProvider`

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.client/src/main/java/org/eclipse/scout/rt/client/opentelemetry/OpenTelemetryPageWithTableExtension.java
> +            .withEventInfo("id", getOwner().getNodeId()));
Maybe the "primaryKey" provides more context:
```suggestion
            .withEventInfo("id", getOwner().getPrimaryKey()));
```

Please verify.

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.client/src/main/java/org/eclipse/scout/rt/client/opentelemetry/OpenTelemetryTreeExtension.java
> +            .withEventInfo("node.text", node.getCell().getText()));
1. Again I think "primaryKey" provides more context, if possible or filled. Attention might be null.
2. I think we should prevent having application data (like customer names, ...) in the traces (span names, span attributes, ...).

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.client/src/main/java/org/eclipse/scout/rt/client/opentelemetry/OpenTelemetryCalendarItemProviderExtension.java
> +            .withEventInfo("item.text", item.getSubject()));
I think we should prevent having application data (like customer names, ...) in the traces (span names, span attributes, ...). Try to use the item's primary key/id instead:
```suggestion
            .withEventInfo("item.text", item.getItemId()));
```

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.client/src/main/java/org/eclipse/scout/rt/client/transformation/DeviceTransformationPlatformListener.java
> +      BEANS.get(IExtensionRegistry.class).register(OpenTelemetryWizardExtension.class);
Register them in a dedicated platform listener implementation and guard the registration with the "tracing" enabled flag.

e.g. `OpenTelemetryUiModelExtensionsPlatformListener` (like `AbstractProfiler.isProfilerModelExtensionsEnabled()`)

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.opentelemetry.sdk/src/test/java/org/eclipse/scout/rt/opentelemetry/sdk/OpenTelemetryInitializerTest.java
> -    GlobalEventEmitterProvider.resetForTest();
Why do we remove this call?

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.platform/src/main/java/org/eclipse/scout/rt/platform/opentelemetry/ScoutOpenTelemetryContextStorage.java
> +public class ScoutOpenTelemetryContextStorage implements ContextStorageProvider, IPlatformListener {
We should briefly describe the purpose of this code.

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.server.commons/src/main/java/org/eclipse/scout/rt/server/commons/opentelemetry/OpenTelemetryFilterInstrumenterFactory.java
> +    Function<SpanStatusExtractor<? super HttpServletRequest, ? super HttpServletResponse>, ? extends SpanStatusExtractor<? super HttpServletRequest, ? super HttpServletResponse>> statusExtractorTrans
This functions do nothing. So can we remove it?

E.g.:
```java
SpanNameExtractor<? super HttpServletRequest> spanNameExtractor = HttpSpanNameExtractor.create(attributesGetter);
```

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.server.commons/src/main/java/org/eclipse/scout/rt/server/commons/opentelemetry/OpenTelemetryFilterInstrumenterFactory.java
> +      return list;
```suggestion
      Enumeration<String> values = httpServletRequest.getHeaders(name);
      return Collections.list(values);
```

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.server.commons/src/main/java/org/eclipse/scout/rt/server/commons/servlet/OpenTelemetryFilter.java
> +
Try to prevent such empty lines between the closing mark (`}`) of the last method and the end of the class.

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.shared/src/main/java/org/eclipse/scout/rt/shared/opentelemetry/HttpServiceTunnelInstrumenterFactory.java
> +        internalSet(attributes, OPERATION, serviceTunnelRequest.getOperation());
Replace `internalSet` by `attributes.put(...)`

2025-01-01 16:55 UTC, brunokoeferli commented on org.eclipse.scout.rt.shared/src/main/java/org/eclipse/scout/rt/shared/opentelemetry/HttpServiceTunnelInstrumenterFactory.java
> +      }
Maybe we need here also the "Parameter-Types" to uniquely identify the called method, see `serviceTunnelRequest.getParameterTypes()`?

2025-01-01 19:45 UTC, brunokoeferli commented on org.eclipse.scout.rt.platform/src/main/java/org/eclipse/scout/rt/platform/opentelemetry/ScoutOpenTelemetryContextStorage.java
> +        Context current = current();
This does not work. This method is only called once and at this time the `BeanManagerValid` state is not matched. So therefore it is always used just the `threadLocalStorage`. And then the context order is not correct (e.g. `ModifyHandler.execLoad`).

```suggestion
    return new ContextStorage() {
      @Override
      public Scope attach(Context toAttach) {
        if (!m_tracingEnabled.get().booleanValue()) {
          return threadLocalStorage.attach(toAttach);
        }

        Context current = current();
```

and:
```java
private LazyValue<Boolean> m_tracingEnabled = new LazyValue<>(() -> CONFIG.getPropertyValue(OpenTelemetryTracingEnabledProperty.class));
```

2025-01-08 07:47 UTC, work-lto commented on org.eclipse.scout.rt.client/src/main/java/org/eclipse/scout/rt/client/extension/ui/basic/tree/AbstractTreeExtension.java
> +
There was a compilation error in OpenTelemetryTreeExtension because it does not implement the inherited abstract method org.eclipse.scout.rt.client.extension.ui.basic.tree.ITreeExtension#execNodesChecked

2025-01-08 07:50 UTC, work-lto commented on org.eclipse.scout.rt.opentelemetry.sdk/src/test/java/org/eclipse/scout/rt/opentelemetry/sdk/OpenTelemetryInitializerTest.java
> -    GlobalEventEmitterProvider.resetForTest();
Class no longer exists

2025-01-26 20:06 UTC, brunokoeferli requested changes

2025-01-26 20:06 UTC, brunokoeferli commented on org.eclipse.scout.rt.client/src/main/java/org/eclipse/scout/rt/client/opentelemetry/OpenTelemetryCalendarItemProviderExtension.java
> +        .withAdditionalAttributesProvider(attributes -> attributes.put(ITEM_TEXT, item.getItemId().toString()))
Do we need a NPE safe implementation?
`item.getItemId().toString()`

2025-01-26 20:06 UTC, brunokoeferli commented on org.eclipse.scout.rt.platform/src/main/java/org/eclipse/scout/rt/platform/opentelemetry/ScoutOpenTelemetryContextStorage.java
> + * the Model Thread. See also: {@link OpenTelemetryContextProcessor}
```suggestion
 * <p>Custom Context Storage implementation such that the OpenTelemetry context is propagated between the Scout's UI and
 * Model Thread. Therefore the RunContext must be kept in sync with the OpenTelemetry context.</p>See also: {@link OpenTelemetryContextProcessor}
```

2025-01-26 20:06 UTC, brunokoeferli commented on org.eclipse.scout.rt.platform/src/main/java/org/eclipse/scout/rt/platform/opentelemetry/ScoutOpenTelemetryContextStorage.java
> +        }
The order should be changed:

```suggestion
        if (!m_tracingEnabled.get().booleanValue()) {
          return threadLocalStorage.attach(toAttach);
        }

        Context current = current();
```

2025-01-26 20:06 UTC, brunokoeferli commented on org.eclipse.scout.rt/pom.xml
> +    <opentelemetry.version>1.44.1</opentelemetry.version>
Again, a new version is available - sorry.

2025-01-30 14:32 UTC, closed without merging

2025-02-11 12:21 UTC, brunokoeferli commented
Follow up for 25/1: https://github.com/eclipse-scout/scout.rt/pull/1357