321048 Improve Tooltip
eclipse-scout/scout.rt pull request #481
Opened 2023-03-08 11:52 UTC by bsifpa

- Scroll tooltip if content is scrolled
 - Prevent tooltip from being displayed without selection

2023-03-16 09:53 UTC, fschinkel requested changes

2023-03-16 09:53 UTC, fschinkel commented on eclipse-scout-core/src/tooltip/Tooltip.js
> +    this.originProducer = null;
I think we need a producer for the offset as well.

originProducer: ($anchor: JQuery) => Rectangle;
offsetProducer: (origin: Rectangle) => Point;

2023-03-16 09:53 UTC, fschinkel commented on eclipse-scout-core/src/tooltip/Tooltip.js
> +    menus.forEach(function (menu) {
please use arrow function

2023-03-16 09:53 UTC, fschinkel commented on eclipse-scout-core/src/tooltip/Tooltip.js
>      if (this.origin) {
```suggestion
    let origin = this._getOrigin(),
      offset = this._getOffset(origin),
      x = origin.x + offset.x,
      y = origin.y + offset.y;
```

and add functions
```javascript
  _getOrigin() {
    if (this.originProducer) {
      const origin = this.originProducer(this.$anchor);
      if (origin) {
        return origin;
      }
    }
    if (this.origin) {
      return this.origin;
    }
    return graphics.offsetBounds(this.$anchor);
  }

  _getOffset(origin) {
    if (this.offsetProducer) {
      const offset = this.offsetProducer(origin);
      if (offset) {
        return offset;
      }
    }
    if (this.origin) {
      return new Point(0, 0);
    }
    return new Point(origin.width / 2, 0);
  }
```

2023-03-16 09:53 UTC, fschinkel commented on eclipse-scout-chart/src/chart/ChartJsRenderer.js
> +      clearTimeout(this._tooltipTimeoutId);
The tooltip will not be rendered until the user stops moving the mouse. This is not the intended behaviour.

2023-03-16 09:53 UTC, fschinkel commented on eclipse-scout-chart/src/chart/ChartJsRenderer.js
> +    let positionAndOffset = this._computeTooltipPositionAndOffset(firstDataPoint);
```javascript
offset = new Point(tooltip.caretX + positionAndOffset.offsetX, tooltip.caretY + positionAndOffset.offsetY)
```

2023-03-16 09:53 UTC, fschinkel commented on eclipse-scout-chart/src/chart/ChartJsRenderer.js
> +      originProducer: this._getTooltipOrigin.bind(this, tooltip)
```suggestion
      originProducer: ($anchor) => {
        const origin = graphics.offsetBounds($anchor);
        origin.height = positionAndOffset.height;
        origin.width = positionAndOffset.width;
        return origin;
      },
      offsetProducer: (origin) => offset
```

2023-03-16 09:53 UTC, fschinkel commented on eclipse-scout-chart/src/chart/ChartJsRenderer.js
> +  _getTooltipOrigin(tooltip) {
remove

2023-03-17 11:00 UTC, bsifpa commented on eclipse-scout-chart/src/chart/ChartJsRenderer.js
> +      clearTimeout(this._tooltipTimeoutId);
It will, because _renderTooltip() is only called once per hovered element

2023-03-17 14:58 UTC, fschinkel approved these changes

2023-03-17 14:58 UTC, fschinkel commented on eclipse-scout-core/src/tooltip/Tooltip.js
> +    tooltipPosition = new Point(origin.x + offset.x, origin.y + offset.y);
```suggestion
    tooltipPosition = origin.point().add(offset);
```

2023-04-12 09:34 UTC, fschinkel approved these changes

2023-04-12 09:46 UTC, merged