Form: add FormValidators
eclipse-scout/scout.rt pull request #785
Opened 2023-11-13 17:37 UTC by fschinkel

A FormValidator is a function that gets the Form and returns a Promise
containing a Status. The Form waits for all validators to be completed
and considers their results while determining if it is valid.
This allows to add asynchronous validators to the Form that e.g. do a
REST call.

344799

2023-12-04 12:06 UTC, cguglielmo requested changes

2023-12-04 12:06 UTC, cguglielmo commented on eclipse-scout-core/src/form/Form.ts
>    _validate(): Status | JQuery.Promise<Status> {
I think it would be better to move the default logic to another function, e.g. _onLifecycleValidate Projects may already override this method without calling super, which breaks the new behavior. Also, js doc needs to be adjusted.

2023-12-04 12:06 UTC, cguglielmo commented on eclipse-scout-core/src/form/Form.ts
> +    if (!this.validators?.length) {
Don't overly use ?. If you initialize with [], it is good enough. If a developer replaces the variable with null it's his fault and fine if his app breaks.

2023-12-04 12:06 UTC, cguglielmo commented on eclipse-scout-core/src/form/Form.ts
> +  setValidators(validators: FormValidator | FormValidator[]) {
add   /** @see FormModel.validators */

2023-12-06 08:25 UTC, mvilliger commented
run tests

2023-12-13 08:54 UTC, merged