MimeType: add missing mime type for mjs
eclipse-scout/scout.rt pull request #944
Opened 2024-03-11 08:21 UTC by fschinkel

377307

2024-03-11 08:55 UTC, mvilliger requested changes
My first question would be: how did we loose this mime type?
Which other mime types have we lost the same way? All these should be added again?

General:
application/javascript is obsolete.
Maybe we should update to the new "text/javascript"? Do all browser support that?
See chapter 6 in https://datatracker.ietf.org/doc/rfc9239/ and this list: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

Mabe we should add all of the common types of the MDN to have the most important ones?

2024-03-11 09:35 UTC, fschinkel commented
> My first question would be: how did we loose this mime type? Which other mime types have we lost the same way? All these should be added again?
> 
> General: application/javascript is obsolete. Maybe we should update to the new "text/javascript"? Do all browser support that? See chapter 6 in https://datatracker.ietf.org/doc/rfc9239/ and https://www.iana.org/assignments/media-types/media-types.xhtml and https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
> 
> Mabe we should add all of the common types of the MDN to have the most important ones?

We lost the mime type by this [commit](https://github.com/eclipse-scout/scout.rt/commit/8cc7f2321955660f6ba60c769b7910d792e3d73a) that deleted the _ServletContextMimeTypeDetector_.
There is a ticket already for those deleting the MimeTypeDetector to fix all other mime types that were lost by that change (see 377371).

2024-03-11 10:06 UTC, mvilliger commented
> 
> We lost the mime type by this [commit](https://github.com/eclipse-scout/scout.rt/commit/8cc7f2321955660f6ba60c769b7910d792e3d73a) that deleted the _ServletContextMimeTypeDetector_. There is a ticket already for those deleting the MimeTypeDetector to fix all other mime types that were lost by that change (see 377371).

I think we should add the missing ones directly now to ensure no other side effects happen instead of delegating that to a later fix?

2024-03-12 11:54 UTC, mvilliger approved these changes

2024-03-12 13:02 UTC, merged