Table: fix tooltip position when rows are updated
eclipse-scout/scout.rt pull request #954
Opened 2024-03-15 15:57 UTC by bschwarzent

When a cell tooltip is open while the row is updated, the tooltip is updated because the new row might have a different tooltip text. Because the tooltip support reuses the same tooltip instance, the $anchor has to be updated as well. Otherwise, the position will be wrong, because the old cell div is no longer in the DOM.

Certain other properties also need to be updated on the existing tooltip instance. For example, if the text is set to an empty string, the tooltip should be closed.

377024

2024-03-19 07:43 UTC, cguglielmo commented on eclipse-scout-core/src/tooltip/TooltipSupport.ts
> +      let anchorChanged = this._tooltip.$anchor !== $anchor;
This is probably always true. You need to compare the html elements.

2024-03-19 07:43 UTC, cguglielmo commented on eclipse-scout-core/src/tooltip/TooltipSupport.ts
> +      this._tooltip.$anchor = $anchor;
I would add setters for the properties on the tooltip class and do the position update in set$Anchor to make it work without a tooltip support as well.

2024-03-26 16:09 UTC, fschinkel requested changes

2024-03-26 16:09 UTC, fschinkel commented on eclipse-scout-core/src/tooltip/TooltipSupport.ts
> +        $anchor: $anchor,
```suggestion
      let options = $.extend({}, this._options, {$anchor, text, htmlEnabled});
```

2024-03-26 16:09 UTC, fschinkel commented on eclipse-scout-core/src/table/Table.ts
> +    if (tooltipSupport && tooltipSupport.tooltip && $row.isOrHas(tooltipSupport.tooltip.$anchor)) {
maybe use ?-notation

2024-03-26 16:09 UTC, fschinkel commented on eclipse-scout-core/src/table/Table.ts
> +      if (tooltipSupport && tooltipSupport.tooltip) {
maybe use ?-notation

2024-03-26 16:09 UTC, fschinkel commented on eclipse-scout-core/src/table/Table.ts
> +      if ($updatedTooltipCell && $updatedTooltipCell.length) {
maybe use ?-notation

2024-03-26 16:09 UTC, fschinkel commented on eclipse-scout-core/src/tooltip/Tooltip.ts
> +    this.$anchor = $anchor;
Is it necessary to position the tooltip if it is not rendered?
Maybe use classic setProperty-render-behaviour.

2024-03-27 12:37 UTC, fschinkel requested changes

2024-03-27 12:37 UTC, fschinkel commented on eclipse-scout-core/src/tooltip/TooltipSupport.ts
> +  get tooltip() {
return type

2024-03-27 12:37 UTC, fschinkel commented on eclipse-scout-core/src/tooltip/Tooltip.ts
> +  _renderHtmlEnabled() {
protected

2024-03-28 15:44 UTC, fschinkel approved these changes

2024-03-30 14:26 UTC, merged